### ISSUE TITLE
Week 6: Drone Image Tracking

### ISSUE THREAD

**Issue by sudowork** [sudowork/nd101-deep-learning#6]
## Lesson
- [ ] Watch lesson
- [ ] Take raw notes
- [ ] Commit raw notes
- [ ] Commit formatted notes

## Live Session
- [ ] Watch lesson
- [ ] Take raw notes
- [ ] Commit raw notes
- [ ] Commit formatted notes
